name: Lastarria
version: '${project.version}'
main: fr.kangpvp.lastarria.Main
api-version: 1.18
authors: [ KangPvP et DraKyx ]
description: yo la team
commands:
  spawn:
  rtp:
    permission: lastarria.use
  ec:
    permission: lastarria.use
  fly:
    permission: lastarria.use
  vanish:
    permission: lastarria.use
  tpall:
    permission: lastarria.use